name: Build Resume

on: push

jobs:
  build:
    if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build resume
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Verify build artifacts
        run: |
          ls -la build/resume.json build/resume.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            build/resume.pdf
            build/resume.json

      - name: Trigger deploy action
        uses: peter-evans/repository-dispatch@v3
        if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.SALISH_DEV_TOKEN }}
          repository: salishdev/salish.dev
          event-type: deploy
